# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='session',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pollgroups.CourseSession'),
            preserve_default=False,
        ),
    ]
