# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollgroups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesession',
            old_name='session_name',
            new_name='pg_name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='organization_name',
            new_name='pg_name',
        ),
    ]
