# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 10:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pollgroups', '0002_auto_20170313_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
