# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 11:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollgroups', '0004_auto_20170314_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesession',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
